name: Build and Release

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build project
        run: cargo build --release

      - name: Upload release asset
        uses: actions/upload-artifact@v4
        with:
          name: ray-windows
          path: target/release/ray.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ray-windows
          path: .

      - name: Extract version from Cargo.toml
        id: cargo-version
        run: echo "VERSION=$(grep '^version =' Cargo.toml | sed -n 's/version = \"\([0-9.]*\)\"/\1/p')" >> $GITHUB_ENV
        shell: bash

      - name: Create GitHub Release
        run: |
          gh release create v${{ env.VERSION }} \
            --title "v${{ env.VERSION }}" \
            ray.exe
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
