name: Build and Release

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test

      - name: Build project
        run: cargo build --release

      - name: Upload release asset
        uses: actions/upload-artifact@v4
        with:
          name: ray-windows
          path: target/release/ray.exe

      - name: Zip winget-pkg folder
        run: |
          if (Test-Path "./winget-pkg") {
            Compress-Archive -Path "./winget-pkg" -DestinationPath "./ray-winget.zip"
          } else {
            Write-Host "winget-pkg folder not found, skipping zip creation"
            echo "null" > ray-winget.zip
          }

      #- name: Upload winget release asset
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: ray-winget
      #    path: ray-winget.zip
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ray-windows
          path: .

      #- name: Download winget artifact
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: ray-winget
      #    path: .

      - name: Extract version from Cargo.toml
        id: cargo-version
        run: echo "VERSION=$(grep '^version =' Cargo.toml | sed -n 's/version = \"\([0-9.]*\)\"/\1/p')" >> $GITHUB_ENV
        shell: bash

      - name: Delete existing release if it exists
        run: |
          if gh release view v${{ env.VERSION }} >/dev/null 2>&1; then
            echo "Release v${{ env.VERSION }} exists, deleting..."
            gh release delete v${{ env.VERSION }} --yes
          else
            echo "Release v${{ env.VERSION }} does not exist"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: Create GitHub Release
        run: |
          gh release create v${{ env.VERSION }} \
          --title "v${{ env.VERSION }}" \
          ray.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
